title: My Github Site

url: "http://notandrewkaye.github.io/my-github-repo"
baseurl: "/my-github-repo"

permalink: pretty

collections:
    portfolio:
        output: true
    gallery:
        output: true
    altBlog:
        output: true

gems:
- jemoji

prose:
  siteurl: 'http://notandrewkaye.github.io/my-github-repo/'
  media: 'img'
  rooturl: '_posts'
  metadata:
    _posts:
      - name: "category"
        field:
          label: "Category"
          element: "text"
          value: "post"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "generic"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Title goes here."
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"